### ISSUE TITLE
TACO Model and Dataset GDrive Links Not working 

### ISSUE THREAD

**Issue by israrulhaq07** [kaylode/trash-segmentation#5]
Hi,
 Thank you for the amazing implementation, could you please share the links for model and dataset for TACO ?

https://drive.google.com/file/d/1XuCem1VaEv4X_IZr1ccgBwoJ_pWM8yRE/view?usp=sharing is not working for model

https://drive.google.com/file/d/1Ol3OcfjAfRul0lxKuV6ezaKP89HXqDMz/view?usp=sharing is not working for dataset.

Links are dead

**Comment by kaylode** [comment]
Thanks for your notification. This repo is for my school project, so now that project has finished, I had deleted some files. Sorry for the inconvenience. You can download the TACO dataset the link that I've just reupload.
For the model pretrained weights, you can find at the original YOLACT author's repo:
https://github.com/dbolya/yolact

**Comment by israrulhaq07** [comment]
Hey, thanks.

Also, could you please add the pretrained model you trained on YOLACT. Link to model is not working.

Thank you

**Comment by kaylode** [comment]
Here is the efficientnet b2 backbone YOLACT that we use in our report: [link](https://drive.google.com/file/d/1-AFqAKaPaS9JbaD2lTautyjltYHaAi3z/view?usp=sharing )

You can use it to inference on testset using this line: 
`python eval.py --config=yolact_plus_taco_efficientnetb2_config  --trained_model=<path to pretrained> --images=<input:output>`

More details can be found at the original repo

**Comment by israrulhaq07** [comment]
thank you.
